pipeline{
    agent any
    stages{
        stage('build-os-details'){
            steps{
                sh '''
                echo "os-details":
                cat /etc/os-release
                '''
            }
        }
        stage('build-memory-details'){
            steps{
                sh '''
                echo "memory-details":
                free -mh
                '''
            }
        }
        stage('build-cpu-details'){
            steps{
                sh '''
                echo "cpu-details":
                lscpu
                '''
            }
        }
        stage('build-private-ip-details'){
            steps{
                sh '''
                echo "private-ip-details":
                hostname -I
                '''
            }
        }
        stage('build--cal-details'){
            steps{
                sh '''
                echo "build-cal-details":
                cal
                '''
            }
        }
   }
}
